{% set version = "2.8.6" %}

package:
  name: psycopg2
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/psycopg2/psycopg2-{{ version }}.tar.gz
  sha256: fb23f6c71107c37fd667cb4ea363ddeb936b348bbd6449278eb92c189699f543
  patches:
    - have_openssl.patch
    # - 0001-fix-library-names-for-openssl-1.1.1-on-win.patch

build:
  number: 2
  ignore_run_exports:
    - openssl
    - krb5  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - patch     # [not win]
    - m2-patch  # [win]
  host:
    - python
    - pip
    - openssl
    - postgresql
    - krb5  # [win]
  run:
    - python
    - libpq

test:
  imports:
    - psycopg2
    - psycopg2._psycopg

about:
  home: https://www.psycopg.org/
  license: LGPL, BSD-like, ZPL
  license_family: LGPL
  license_file: LICENSE
  summary: PostgreSQL database adapter for Python
  description: |
    Psycopg is the most popular PostgreSQL adapter for the Python programming
    language. Its main features are the complete implementation of the Python DB
    API 2.0 specification and the thread safety.
  doc_url: https://www.psycopg.org/docs/
  doc_source_url: https://github.com/psycopg/psycopg2/blob/master/doc/src/index.rst
  dev_url: https://github.com/psycopg/psycopg2/

extra:
  recipe-maintainers:
    - msarahan
    - ocefpaf
