{% set version = "2.8" %}

package:
  name: psycopg2
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/psycopg2/psycopg2-{{ version }}.tar.gz
  sha256: 49c5838d90e83217909db3789d30a105385b5e696ec5168cda645546c542f35a
  patches:
    - have_openssl.patch

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - openssl
    - postgresql
  run:
    - python
    # libpq is a repackaging of only the library to connect to postgres
    - libpq
    - openssl

test:
  imports:
    - psycopg2
    - psycopg2._psycopg

about:
  home: http://initd.org/psycopg/
  license: LGPL, BSD-like, ZPL
  license_family: LGPL
  license_file: LICENSE
  summary: PostgreSQL database adapter for Python
  description: |
    Psycopg is the most popular PostgreSQL adapter for the Python programming
    language. Its main features are the complete implementation of the Python DB
    API 2.0 specification and the thread safety.
  doc_url: http://initd.org/psycopg/docs/
  doc_source_url: https://github.com/psycopg/psycopg2/blob/master/doc/src/index.rst
  dev_url: https://github.com/psycopg/psycopg2/

extra:
  recipe-maintainers:
    - msarahan
    - ocefpaf
