{% set version = "2.6.1" %}

package:
    name: psycopg2
    version: {{ version }}

source:
    fn: psycopg2-{{ version }}.tar.gz
    url: https://pypi.python.org/packages/source/p/psycopg2/psycopg2-{{ version }}.tar.gz
    md5: 842b44f8c95517ed5b792081a2370da1
    patches:
        - have_openssl.patch
        # VS 2013+ have built-in support for round, which conflicts with definition in psycopg.
        - round_msvc.patch  # [win and py>=35]

build:
    number: 1

requirements:
    build:
        - openssl 1.0.*
        - postgresql
        - python
    run:
        # libpq is a repackaging of only the library to connect to postgres
        - libpq
        - openssl 1.0.*
        - python

test:
    imports:
        - psycopg2
        - psycopg2._psycopg

about:
    home: http://initd.org/psycopg/
    license: LGPL, BSD-like, ZPL
    summary: Python-PostgreSQL Database Adapter

extra:
    recipe-maintainers:
        - msarahan
        - ocefpaf
