{% set version = "2.7.4" %}
{% set sha256 = "8bf51191d60f6987482ef0cfe8511bbf4877a5aa7f313d7b488b53189cf26209" %}

package:
  name: psycopg2
  version: {{ version }}

source:
  fn: psycopg2-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/psycopg2/psycopg2-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - have_openssl.patch

build:
  number: 0
  script: python setup.py install  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - openssl
    - postgresql
  run:
    - python
    # libpq and openssl are added via run_exports

test:
  imports:
    - psycopg2
    - psycopg2._psycopg

about:
  home: http://initd.org/psycopg/
  license: LGPL, BSD-like, ZPL
  license_family: LGPL
  license_file: LICENSE
  summary: PostgreSQL database adapter for Python
  description: |
    Psycopg is the most popular PostgreSQL adapter for the Python programming
    language. Its main features are the complete implementation of the Python DB
    API 2.0 specification and the thread safety.
  doc_url: http://initd.org/psycopg/docs/
  doc_source_url: https://github.com/psycopg/psycopg2/blob/master/doc/src/index.rst
  dev_url: https://github.com/psycopg/psycopg2/

extra:
  recipe-maintainers:
    - msarahan
    - ocefpaf
