{% set version = "2.9.9" %}

package:
  name: psycopg2
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/psycopg2/psycopg2-{{ version }}.tar.gz
  sha256: d1454bde93fb1e224166811694d600e746430c006fbb031ea06ecc2ea41bf156
  patches:
    - have_openssl.patch

build:
  skip: true  # [py<37]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - patch     # [not win]
    - m2-patch  # [win]
  host:
    - python
    - pip
    - wheel
    - setuptools
    - libpq 12.15
  run:
    - python
    - libpq

test:
  imports:
    - psycopg2
    - psycopg2._psycopg
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.psycopg.org/
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: PostgreSQL database adapter for Python
  description: |
    Psycopg is the most popular PostgreSQL adapter for the Python programming
    language. Its main features are the complete implementation of the Python DB
    API 2.0 specification and the thread safety.
  doc_url: https://www.psycopg.org/docs/
  dev_url: https://github.com/psycopg/psycopg2/

extra:
  recipe-maintainers:
    - msarahan
    - ocefpaf
