travis:
  secure:
    BINSTAR_TOKEN: ng8B2rUd5G0eqE25RYlrlyoJvWQeAo4qnzT22obYgm3bu8Xv4Tg7EepFQCPaNTrUiMu4UDfpHFG6mm/8DIo/TTM1z0v2/nVxSbq+r/FBUV2jA4K/zLG+iy+wBeWRZada28BDM+SVNJynOUzVheM+UGP+82It1HT7ojrVud/HoDyWm+LCe/QCuCr8yQAd2rruuTnHXG5mE+seZCkneHMMoax9EjlvyhzwoCbTgWY4JTzStyfg+qJ+gLXl7HttBaEfQc+ml1NHEuhe03fyUeiBKQRGj7rgoI2xQ7Agqk4X8DujPxnqr50Y5m5ezW6oCsv+Q2Bvuwd3P8ToOm5f8zmYJAmmt81uQ+lH7TWU5KetszW/99U+DxAaGa9Gkq8IkAaqtLJ7heYtOgS/wRBNCeyfm78g8kSvztffu5kdoiSCD4xMV3YlQJQHRbv1H9/JyMTdecOz0WBIdpM38dLOSGlg/5y+HKexSIqiwoemaDLbdUbjCHhSk+1bzTqvaoLDAPzIwV6ADn1TqOu7xflNI5opOIryvBEYwcP4O3b6Gzjxh89boo7sEY2gSa8Vj/7fhK9qR2pNsJDU+xm1G1+ka+letppp6cbbpZYtWfX3QkUK1J/yig1azcxGWr9DCYDINIwYv7lYDGL2oKYscRZsDVsJnBFRdK4RoXzz7Ac7Zpi5070=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
